/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package carldata.hs.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BatchRecordAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 257575359675080661L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BatchRecordAvro\",\"namespace\":\"carldata.hs.avro\",\"fields\":[{\"name\":\"calculationId\",\"type\":\"string\"},{\"name\":\"script\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"inputChannelId\",\"type\":\"string\"},{\"name\":\"outputChannelId\",\"type\":\"string\"},{\"name\":\"startDate\",\"type\":\"string\"},{\"name\":\"endDate\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BatchRecordAvro> ENCODER =
      new BinaryMessageEncoder<BatchRecordAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BatchRecordAvro> DECODER =
      new BinaryMessageDecoder<BatchRecordAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BatchRecordAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BatchRecordAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BatchRecordAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BatchRecordAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BatchRecordAvro from a ByteBuffer. */
  public static BatchRecordAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence calculationId;
  @Deprecated public java.util.List<java.lang.CharSequence> script;
  @Deprecated public java.lang.CharSequence inputChannelId;
  @Deprecated public java.lang.CharSequence outputChannelId;
  @Deprecated public java.lang.CharSequence startDate;
  @Deprecated public java.lang.CharSequence endDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BatchRecordAvro() {}

  /**
   * All-args constructor.
   * @param calculationId The new value for calculationId
   * @param script The new value for script
   * @param inputChannelId The new value for inputChannelId
   * @param outputChannelId The new value for outputChannelId
   * @param startDate The new value for startDate
   * @param endDate The new value for endDate
   */
  public BatchRecordAvro(java.lang.CharSequence calculationId, java.util.List<java.lang.CharSequence> script, java.lang.CharSequence inputChannelId, java.lang.CharSequence outputChannelId, java.lang.CharSequence startDate, java.lang.CharSequence endDate) {
    this.calculationId = calculationId;
    this.script = script;
    this.inputChannelId = inputChannelId;
    this.outputChannelId = outputChannelId;
    this.startDate = startDate;
    this.endDate = endDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return calculationId;
    case 1: return script;
    case 2: return inputChannelId;
    case 3: return outputChannelId;
    case 4: return startDate;
    case 5: return endDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: calculationId = (java.lang.CharSequence)value$; break;
    case 1: script = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: inputChannelId = (java.lang.CharSequence)value$; break;
    case 3: outputChannelId = (java.lang.CharSequence)value$; break;
    case 4: startDate = (java.lang.CharSequence)value$; break;
    case 5: endDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'calculationId' field.
   * @return The value of the 'calculationId' field.
   */
  public java.lang.CharSequence getCalculationId() {
    return calculationId;
  }

  /**
   * Sets the value of the 'calculationId' field.
   * @param value the value to set.
   */
  public void setCalculationId(java.lang.CharSequence value) {
    this.calculationId = value;
  }

  /**
   * Gets the value of the 'script' field.
   * @return The value of the 'script' field.
   */
  public java.util.List<java.lang.CharSequence> getScript() {
    return script;
  }

  /**
   * Sets the value of the 'script' field.
   * @param value the value to set.
   */
  public void setScript(java.util.List<java.lang.CharSequence> value) {
    this.script = value;
  }

  /**
   * Gets the value of the 'inputChannelId' field.
   * @return The value of the 'inputChannelId' field.
   */
  public java.lang.CharSequence getInputChannelId() {
    return inputChannelId;
  }

  /**
   * Sets the value of the 'inputChannelId' field.
   * @param value the value to set.
   */
  public void setInputChannelId(java.lang.CharSequence value) {
    this.inputChannelId = value;
  }

  /**
   * Gets the value of the 'outputChannelId' field.
   * @return The value of the 'outputChannelId' field.
   */
  public java.lang.CharSequence getOutputChannelId() {
    return outputChannelId;
  }

  /**
   * Sets the value of the 'outputChannelId' field.
   * @param value the value to set.
   */
  public void setOutputChannelId(java.lang.CharSequence value) {
    this.outputChannelId = value;
  }

  /**
   * Gets the value of the 'startDate' field.
   * @return The value of the 'startDate' field.
   */
  public java.lang.CharSequence getStartDate() {
    return startDate;
  }

  /**
   * Sets the value of the 'startDate' field.
   * @param value the value to set.
   */
  public void setStartDate(java.lang.CharSequence value) {
    this.startDate = value;
  }

  /**
   * Gets the value of the 'endDate' field.
   * @return The value of the 'endDate' field.
   */
  public java.lang.CharSequence getEndDate() {
    return endDate;
  }

  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(java.lang.CharSequence value) {
    this.endDate = value;
  }

  /**
   * Creates a new BatchRecordAvro RecordBuilder.
   * @return A new BatchRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.BatchRecordAvro.Builder newBuilder() {
    return new carldata.hs.avro.BatchRecordAvro.Builder();
  }

  /**
   * Creates a new BatchRecordAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BatchRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.BatchRecordAvro.Builder newBuilder(carldata.hs.avro.BatchRecordAvro.Builder other) {
    return new carldata.hs.avro.BatchRecordAvro.Builder(other);
  }

  /**
   * Creates a new BatchRecordAvro RecordBuilder by copying an existing BatchRecordAvro instance.
   * @param other The existing instance to copy.
   * @return A new BatchRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.BatchRecordAvro.Builder newBuilder(carldata.hs.avro.BatchRecordAvro other) {
    return new carldata.hs.avro.BatchRecordAvro.Builder(other);
  }

  /**
   * RecordBuilder for BatchRecordAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BatchRecordAvro>
    implements org.apache.avro.data.RecordBuilder<BatchRecordAvro> {

    private java.lang.CharSequence calculationId;
    private java.util.List<java.lang.CharSequence> script;
    private java.lang.CharSequence inputChannelId;
    private java.lang.CharSequence outputChannelId;
    private java.lang.CharSequence startDate;
    private java.lang.CharSequence endDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(carldata.hs.avro.BatchRecordAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.calculationId)) {
        this.calculationId = data().deepCopy(fields()[0].schema(), other.calculationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.script)) {
        this.script = data().deepCopy(fields()[1].schema(), other.script);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inputChannelId)) {
        this.inputChannelId = data().deepCopy(fields()[2].schema(), other.inputChannelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.outputChannelId)) {
        this.outputChannelId = data().deepCopy(fields()[3].schema(), other.outputChannelId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.startDate)) {
        this.startDate = data().deepCopy(fields()[4].schema(), other.startDate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.endDate)) {
        this.endDate = data().deepCopy(fields()[5].schema(), other.endDate);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BatchRecordAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(carldata.hs.avro.BatchRecordAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.calculationId)) {
        this.calculationId = data().deepCopy(fields()[0].schema(), other.calculationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.script)) {
        this.script = data().deepCopy(fields()[1].schema(), other.script);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inputChannelId)) {
        this.inputChannelId = data().deepCopy(fields()[2].schema(), other.inputChannelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.outputChannelId)) {
        this.outputChannelId = data().deepCopy(fields()[3].schema(), other.outputChannelId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.startDate)) {
        this.startDate = data().deepCopy(fields()[4].schema(), other.startDate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.endDate)) {
        this.endDate = data().deepCopy(fields()[5].schema(), other.endDate);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'calculationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCalculationId() {
      return calculationId;
    }

    /**
      * Sets the value of the 'calculationId' field.
      * @param value The value of 'calculationId'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setCalculationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.calculationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'calculationId' field has been set.
      * @return True if the 'calculationId' field has been set, false otherwise.
      */
    public boolean hasCalculationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'calculationId' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearCalculationId() {
      calculationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'script' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getScript() {
      return script;
    }

    /**
      * Sets the value of the 'script' field.
      * @param value The value of 'script'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setScript(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.script = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'script' field has been set.
      * @return True if the 'script' field has been set, false otherwise.
      */
    public boolean hasScript() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'script' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearScript() {
      script = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'inputChannelId' field.
      * @return The value.
      */
    public java.lang.CharSequence getInputChannelId() {
      return inputChannelId;
    }

    /**
      * Sets the value of the 'inputChannelId' field.
      * @param value The value of 'inputChannelId'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setInputChannelId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.inputChannelId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'inputChannelId' field has been set.
      * @return True if the 'inputChannelId' field has been set, false otherwise.
      */
    public boolean hasInputChannelId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'inputChannelId' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearInputChannelId() {
      inputChannelId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'outputChannelId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOutputChannelId() {
      return outputChannelId;
    }

    /**
      * Sets the value of the 'outputChannelId' field.
      * @param value The value of 'outputChannelId'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setOutputChannelId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.outputChannelId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'outputChannelId' field has been set.
      * @return True if the 'outputChannelId' field has been set, false otherwise.
      */
    public boolean hasOutputChannelId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'outputChannelId' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearOutputChannelId() {
      outputChannelId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'startDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartDate() {
      return startDate;
    }

    /**
      * Sets the value of the 'startDate' field.
      * @param value The value of 'startDate'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setStartDate(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.startDate = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'startDate' field has been set.
      * @return True if the 'startDate' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'startDate' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearStartDate() {
      startDate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getEndDate() {
      return endDate;
    }

    /**
      * Sets the value of the 'endDate' field.
      * @param value The value of 'endDate'.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder setEndDate(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.endDate = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'endDate' field has been set.
      * @return True if the 'endDate' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'endDate' field.
      * @return This builder.
      */
    public carldata.hs.avro.BatchRecordAvro.Builder clearEndDate() {
      endDate = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BatchRecordAvro build() {
      try {
        BatchRecordAvro record = new BatchRecordAvro();
        record.calculationId = fieldSetFlags()[0] ? this.calculationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.script = fieldSetFlags()[1] ? this.script : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.inputChannelId = fieldSetFlags()[2] ? this.inputChannelId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.outputChannelId = fieldSetFlags()[3] ? this.outputChannelId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.startDate = fieldSetFlags()[4] ? this.startDate : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.endDate = fieldSetFlags()[5] ? this.endDate : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BatchRecordAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<BatchRecordAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BatchRecordAvro>
    READER$ = (org.apache.avro.io.DatumReader<BatchRecordAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
