/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package carldata.hs.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventBusRecordAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 192531963067327689L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventBusRecordAvro\",\"namespace\":\"carldata.hs.avro\",\"fields\":[{\"name\":\"calculationId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"EventBusRecordStatusAvro\",\"symbols\":[\"BatchCalculationStarted\",\"BatchCalculationStopped\",\"Unknown\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventBusRecordAvro> ENCODER =
      new BinaryMessageEncoder<EventBusRecordAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventBusRecordAvro> DECODER =
      new BinaryMessageDecoder<EventBusRecordAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EventBusRecordAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EventBusRecordAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventBusRecordAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EventBusRecordAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EventBusRecordAvro from a ByteBuffer. */
  public static EventBusRecordAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence calculationId;
  @Deprecated public carldata.hs.avro.EventBusRecordStatusAvro status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventBusRecordAvro() {}

  /**
   * All-args constructor.
   * @param calculationId The new value for calculationId
   * @param status The new value for status
   */
  public EventBusRecordAvro(java.lang.CharSequence calculationId, carldata.hs.avro.EventBusRecordStatusAvro status) {
    this.calculationId = calculationId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return calculationId;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: calculationId = (java.lang.CharSequence)value$; break;
    case 1: status = (carldata.hs.avro.EventBusRecordStatusAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'calculationId' field.
   * @return The value of the 'calculationId' field.
   */
  public java.lang.CharSequence getCalculationId() {
    return calculationId;
  }

  /**
   * Sets the value of the 'calculationId' field.
   * @param value the value to set.
   */
  public void setCalculationId(java.lang.CharSequence value) {
    this.calculationId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public carldata.hs.avro.EventBusRecordStatusAvro getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(carldata.hs.avro.EventBusRecordStatusAvro value) {
    this.status = value;
  }

  /**
   * Creates a new EventBusRecordAvro RecordBuilder.
   * @return A new EventBusRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.EventBusRecordAvro.Builder newBuilder() {
    return new carldata.hs.avro.EventBusRecordAvro.Builder();
  }

  /**
   * Creates a new EventBusRecordAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventBusRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.EventBusRecordAvro.Builder newBuilder(carldata.hs.avro.EventBusRecordAvro.Builder other) {
    return new carldata.hs.avro.EventBusRecordAvro.Builder(other);
  }

  /**
   * Creates a new EventBusRecordAvro RecordBuilder by copying an existing EventBusRecordAvro instance.
   * @param other The existing instance to copy.
   * @return A new EventBusRecordAvro RecordBuilder
   */
  public static carldata.hs.avro.EventBusRecordAvro.Builder newBuilder(carldata.hs.avro.EventBusRecordAvro other) {
    return new carldata.hs.avro.EventBusRecordAvro.Builder(other);
  }

  /**
   * RecordBuilder for EventBusRecordAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventBusRecordAvro>
    implements org.apache.avro.data.RecordBuilder<EventBusRecordAvro> {

    private java.lang.CharSequence calculationId;
    private carldata.hs.avro.EventBusRecordStatusAvro status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(carldata.hs.avro.EventBusRecordAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.calculationId)) {
        this.calculationId = data().deepCopy(fields()[0].schema(), other.calculationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EventBusRecordAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(carldata.hs.avro.EventBusRecordAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.calculationId)) {
        this.calculationId = data().deepCopy(fields()[0].schema(), other.calculationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'calculationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCalculationId() {
      return calculationId;
    }

    /**
      * Sets the value of the 'calculationId' field.
      * @param value The value of 'calculationId'.
      * @return This builder.
      */
    public carldata.hs.avro.EventBusRecordAvro.Builder setCalculationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.calculationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'calculationId' field has been set.
      * @return True if the 'calculationId' field has been set, false otherwise.
      */
    public boolean hasCalculationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'calculationId' field.
      * @return This builder.
      */
    public carldata.hs.avro.EventBusRecordAvro.Builder clearCalculationId() {
      calculationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public carldata.hs.avro.EventBusRecordStatusAvro getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public carldata.hs.avro.EventBusRecordAvro.Builder setStatus(carldata.hs.avro.EventBusRecordStatusAvro value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public carldata.hs.avro.EventBusRecordAvro.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventBusRecordAvro build() {
      try {
        EventBusRecordAvro record = new EventBusRecordAvro();
        record.calculationId = fieldSetFlags()[0] ? this.calculationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (carldata.hs.avro.EventBusRecordStatusAvro) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventBusRecordAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventBusRecordAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventBusRecordAvro>
    READER$ = (org.apache.avro.io.DatumReader<EventBusRecordAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
