/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package carldata.hs.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventBusRecordStatusAvro {
  BatchCalculationStarted, BatchCalculationStopped, Unkown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventBusRecordStatusAvro\",\"namespace\":\"carldata.hs.avro\",\"symbols\":[\"BatchCalculationStarted\",\"BatchCalculationStopped\",\"Unkown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
