/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package carldata.hs.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum RealTimeRecordActionAvro {
  AddAction, RemoveAction, UnknownAction  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RealTimeRecordActionAvro\",\"namespace\":\"carldata.hs.avro\",\"symbols\":[\"AddAction\",\"RemoveAction\",\"UnknownAction\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
